name: requests
description: A starting point for Dart libraries or applications.
version: 2.0.1
homepage: https://github.com/jossef/requests
author: Jossef Harush <jossef12@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0
  shared_preferences: ^0.5.2
  crypto: ^2.0.6
  hex: ^0.1.2
  logging: ^0.11.3+2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.0.0
  test: ^1.0.0
