name: requests
description: a flutter library that helps with http requests and stored cookies
version: 4.2.0
homepage: https://github.com/jossef/requests
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  crypto: ^3.0.1
  hex: ^0.2.0
  http: ^0.13.4
  logging: ^1.0.2
  hive: ^2.1.0
  stash: ^4.0.1
  stash_hive : ^4.0.1
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
