name: requests_plus
description: a flutter library that helps with http requests and stored cookies
version: 4.8.0
homepage: https://github.com/onyx-lyon1/requests_plus
environment:
  sdk: '>=2.16.1 <3.1.0'
dependencies:
  crypto: ^3.0.3
  hex: ^0.2.0
  http: <=1.1.0
  quiver: ^3.2.1
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
