name: requests
description: a flutter library that helps with http requests and stored cookies
version: 5.0.0
homepage: https://github.com/jossef/requests
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  crypto: ^3.0.3
  hex: ^0.2.0
  http: ^1.0.0
  quiver: ^3.2.1
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
